<font size=6 color="#0098CD">
Trabajo: Eliminación gaussiana
</font>

---

**Asignatura:** Álgebra Lineal

**Presentado por:** *Ronaldo Jimenéz Acosta*

**Fecha:** 9 - Nov - 2022

--- 

### 1. Objetivos
* Aplicar  los  conceptos  abordados  en  los  temas  1  y  2,  específicamente,  aquellos 
relacionados con solución de sistemas de ecuaciones lineales.

* Utilizar el lenguaje de programación Python para realizar cálculos básicos, 
representaciones gráficas en 3D y operaciones con matrices.

### 2. Descripción de la actividad y pautas de elaboración
A continuación, se plantean tres sistemas de ecuaciones lineales que deben 
resolverse aplicando los conceptos y procedimientos abordados en los temas 1 y 2. 
La entrega debe hacerse **únicamente en formato PDF**. Extensión máxima: 10 páginas.

#### Sistema de ecuaciones 1 $\color{green}{\text{(3 puntos)}}$

>$2x - y + 3z = 16$
>
>$4x + 0y - 2z = -4$
>
>$x + 3y - z = -9$


a) Traza  las  gráficas  de  las  tres  ecuaciones  en  el  mismo  sistema  de  coordenadas 
cartesianas.  ¿Qué  se  puede  afirmar  sobre  la  solución  del  sistema?  Explica  tu 
respuesta.

> **R/=** En el punto $(1, -2,  4)$ X, Y, Z, respectivamente es el punto de cruce de las 3 ecuaciones, por lo tanto es la solución al sistema.

In [ ]:
from IPython.display import IFrame

IFrame(src="https://www.geogebra.org/3d?lang=es",
       width=1080, height=600)

![img_grafica_1](https://user-images.githubusercontent.com/53100460/199523967-06e506f1-38ce-4de3-8bbc-5df8dc5d7d6d.png)

b) Resuelve  el  sistema  aplicando  el  método  de  Gauss.  Registra  el  procedimiento 
paso a paso y la solución.

In [3]:
import numpy as np
print('# 1. expresar el sistema de ecuaciones lineales como una matriz aumentada')
A = np.array([[2,-1,3,16],[4,0,-2,-4],[1,3,-1,-9]])
print(A)
print()

print('# 2. intercambiamos la fila 3 por la fila 1 (F3 <--> F1)')
A = np.array([[1,3,-1,-9],[4,0,-2,-4],[2,-1,3,16]])
print(A)
print()

print('# 3. para obtener el primer 0 hacemos: F2 - 4F1')
F2 = A[1] - 4*A[0]
print(F2)
print('simplicamos')
F2_s = F2/2
print(F2_s)
print()

print('# 4. primer 0 conseguido')
A[1] = F2_s
print(A)
print()

print('# 5. para obtener el segundo 0 hacemos: F3 - 2F1')
F3 = A[2] - 2*A[0]
print(F3)
print()

print('# 6. segundo 0 conseguido')
A[2] = F3
print(A)
print()

print('# 7. para obtener el tercer 0 hacemos: 6F3 - 7F2')
F3_2 = 6*A[2] - 7*A[1]
print(F3_2)
print()

print('# 8. tercer 0 conseguido')
A[2] = F3_2
print(A)
print()

# 1. expresar el sistema de ecuaciones lineales como una matriz aumentada
[[ 2 -1  3 16]
 [ 4  0 -2 -4]
 [ 1  3 -1 -9]]

# 2. intercambiamos la fila 3 por la fila 1 (F3 <--> F1)
[[ 1  3 -1 -9]
 [ 4  0 -2 -4]
 [ 2 -1  3 16]]

# 3. para obtener el primer 0 hacemos: F2 - 4F1
[  0 -12   2  32]
simplicamos
[ 0. -6.  1. 16.]

# 4. primer 0 conseguido
[[ 1  3 -1 -9]
 [ 0 -6  1 16]
 [ 2 -1  3 16]]

# 5. para obtener el segundo 0 hacemos: F3 - 2F1
[ 0 -7  5 34]

# 6. segundo 0 conseguido
[[ 1  3 -1 -9]
 [ 0 -6  1 16]
 [ 0 -7  5 34]]

# 7. para obtener el tercer 0 hacemos: 6F3 - 7F2
[ 0  0 23 92]

# 8. tercer 0 conseguido
[[ 1  3 -1 -9]
 [ 0 -6  1 16]
 [ 0  0 23 92]]




c) Obtén  la  solución  del  sistema  usando  **numpy.linalg.solve**.  Compara  esta 
solución con la obtenida en el literal b).

In [30]:
import numpy as np
# Matriz A
A = np.array([[2, -1, 3], [4, 0, -2], [1, 3, -1]])
# Vector b
b = np.array([16, -4, -9])
# Solución
x = np.linalg.solve(A, b)
print(x)
print('Comprobamos que A * x = b')
print(np.matmul(A, x))

[ 1. -2.  4.]
Comprobamos que A * x = b
[16. -4. -9.]


**Solución:**

>$\begin{bmatrix}
> X &\\
> Y &\\
> Z 
> \end{bmatrix}$
> $=$ 
> $\begin{bmatrix}
> 1 &\\
> -2 &\\
> 4 
> \end{bmatrix}$

#### Sistema de ecuaciones 2 $\color{green}{\text{(3 puntos)}}$

>$x + 5y - z = 7$
>
>$2x - y + 3z = 10$
>
>$3x + 4y + 2z = 4$

a) Traza  las  gráficas  de  las  tres  ecuaciones  en  el  mismo  sistema  de  coordenadas 
cartesianas.  ¿Qué  se  puede  afirmar  sobre  la  solución  del  sistema?  Explica  tu 
respuesta.

> **R/=** No tiene solución porque se evidencia que no existe un corte en los 3 ejes $(x,y,z)$, ademas al resolver el punto b, se evidencia que la variable $Z$ se elimina (su valor es 0z), por lo tanto el sistema no se puede resolver.

![img_grafica_2](https://user-images.githubusercontent.com/53100460/199739320-5a4c8939-7716-4f12-901c-07d337f0fcd7.png)

b) Resuelve  el  sistema  aplicando  el  método  de  Gauss.  Registra  el  procedimiento 
paso a paso y la solución.

In [4]:
import numpy as np
print('# 1. expresar el sistema de ecuaciones lineales como una matriz aumentada')
A = np.array([[1,5,-1,7],[2,-1,3,10],[3,4,2,4]])
print(A)
print()

print('# 2. para obtener el primer 0 hacemos: F2 - 2F1')
F2 = A[1] - 2*A[0]
print(F2)
print()

print('# 3. primer 0 conseguido')
A[1] = F2
print(A)
print()

print('# 4. para obtener el segundo 0 hacemos: F3 - 3F1')
F3 = A[2] - 3*A[0]
print(F3)
print()

print('# 5. segundo 0 conseguido')
A[2] = F3
print(A)
print()

print('# 6. para obtener el tercer 0 hacemos: F3 - F2')
F3_2 = A[2] - A[1]
print(F3_2)
print()

print('# 7. tercer 0 conseguido')
A[2] = F3_2
print(A)
print()

# 1. expresar el sistema de ecuaciones lineales como una matriz aumentada
[[ 1  5 -1  7]
 [ 2 -1  3 10]
 [ 3  4  2  4]]

# 2. para obtener el primer 0 hacemos: F2 - 2F1
[  0 -11   5  -4]

# 3. primer 0 conseguido
[[  1   5  -1   7]
 [  0 -11   5  -4]
 [  3   4   2   4]]

# 4. para obtener el segundo 0 hacemos: F3 - 3F1
[  0 -11   5 -17]

# 5. segundo 0 conseguido
[[  1   5  -1   7]
 [  0 -11   5  -4]
 [  0 -11   5 -17]]

# 6. para obtener el tercer 0 hacemos: F3 - F2
[  0   0   0 -13]

# 7. tercer 0 conseguido
[[  1   5  -1   7]
 [  0 -11   5  -4]
 [  0   0   0 -13]]



c) Obtén  la  solución  del  sistema  usando  **numpy.linalg.solve**.  Compara  esta 
solución con la obtenida en el literal b).

In [1]:
import numpy as np
# Matriz A
A = np.array([[1, 5, -1], [2, -1, 3], [3, 4, 2]])
# Vector b
b = np.array([7, 10, 4])
# Solución
x = np.linalg.solve(A, b)
print(x)
print('Comprobamos que A * x = b')
print(np.matmul(A, x))

[-3.72570515e+16  1.33060898e+16  2.92733976e+16]
Comprobamos que A * x = b
[ 0.  0. -8.]


#### Solución:
> Considerando el resultado  en la tercera fila $[  0,  0,  0, -13]$ de la matriz(), el sistema no tiene solución.

#### Sistema de ecuaciones 3 $\color{green}{\text{(3 puntos)}}$

>$-2x + 3y + z = 5$
>
>$2x + y - 3z = 12$
>
>$4x - 2y - 4z = 7$

a) Traza  las  gráficas  de  las  tres  ecuaciones  en  el  mismo  sistema  de  coordenadas 
cartesianas.  ¿Qué  se  puede  afirmar  sobre  la  solución  del  sistema?  Explica  tu 
respuesta.

>**R/=** Se puede evidenciar que no existe un corte en los ejes (x,y,z). Su determinante es 0, por lo tanto se define como una matriz singular.

![grafica_punto_3](https://user-images.githubusercontent.com/53100460/199748972-0e4d038b-f2f4-4baa-b5ed-c0d853c7dd70.png)

b) Resuelve  el  sistema  aplicando  el  método  de  Gauss.  Registra  el  procedimiento 
paso a paso y la solución.

In [7]:
import numpy as np
A = np.array([[-2, 3, 1], [2, 1, -3], [4, -2, -4]])
print(A)
determinante = np.linalg.det(A)
print(f'El determinante de la Matriz A es: {determinante}')
print(f'Como el valor del determinante es {determinante}, esto quiere decir que es una matriz singular, por lo tanto no se puede resolver')
print()

A = np.array([[-2, 3, 1, 5], [2, 1, -3, 12], [4, -2, -4, 7]])
print('# 1. para obtener el primer 0 hacemos: F2 + F1')
F2 = A[1] + A[0]
A[1] = F2
print(A)
print()

print('# 2. para obtener el segundo 0 hacemos: F3 + 2F1')
F3 = A[2] + 2*A[0]
A[2] = F3
print(A)
print()

print('# 3. para obtener el tercer 0 hacemos: F3 - F2')
F3_2 = A[2] - A[1]
A[2] = F3_2
print(A)

[[-2  3  1]
 [ 2  1 -3]
 [ 4 -2 -4]]
El determinante de la Matriz A es: 0.0
Como el valor del determinante es 0.0, esto quiere decir que es una matriz singular, por lo tanto no se puede resolver

# 1. para obtener el primer 0 hacemos: F2 + F1
[[-2  3  1  5]
 [ 0  4 -2 17]
 [ 4 -2 -4  7]]

# 2. para obtener el segundo 0 hacemos: F3 + 2F1
[[-2  3  1  5]
 [ 0  4 -2 17]
 [ 0  4 -2 17]]

# 3. para obtener el tercer 0 hacemos: F3 - F2
[[-2  3  1  5]
 [ 0  4 -2 17]
 [ 0  0  0  0]]


c) Obtén  la  solución  del  sistema  usando  numpy.linalg.solve.  Compara  esta 
solución con la obtenida en el literal b).

In [9]:
import numpy as np
try:
    # Matriz A
    A = np.array([[-2, 3, 1], [2, 1, -3], [4, -2, -4]])
    # Vector b
    b = np.array([5, 12, 7])
    # Solución
    x = np.linalg.solve(A, b)
    print(x)
    print('Comprobamos que A * x = b')
    print(np.matmul(A, x))
except Exception as e:
    print(f'Ha ocurrido una exepción: {e}')


Ha ocurrido una exepción: Singular matrix


#### Solución:
> Considerando el resultado  en la tercera fila $[  0,  0,  0, 0]$ de la matriz(), el sistema no tiene solución.

#### Conclusiones $\color{green}{\text{(1 puntos)}}$
Registra  dos  o  tres  conclusiones  sobre  esta  actividad.  Considera:  los  conceptos 
abordados, los problemas propuestos y el uso de Python para la solución.

> * He aprendido a identificar las diferentes tipos de matrices(matriz fila, matriz columna, matriz nula, matriz cuadrada) y a realizar operaciones entre matrices (suma, resta, producto por un escalar  y producto matricial). 
>
> * He aprendido a utilizar las herramientas tecnológicas como apoyo y medios para resolver estos sistemas (Geogebra, Google Colab, MarkDown, Python, Jupyter Notebooks y Git-GitHub) 
>
> * Expresar un sistema de ecuaciones como una matriz e identificar si tiene solución o no (por ejemplo, una matriz singular). Cuando una matriz (x) es multiplicada por la matriz identidad (I) como resultado obtemos la misma matrziz (x)

#### Repositoro del trabajo:
> [Eliminacion_gaussina.ipynb](https://github.com/JimcostDev/Mis_Apuntes_Algebra_Lineal/blob/master/Trabajo-1/Eliminacion_gaussiana.ipynb)