<font size=6 color="#0098CD">
Álgebra Lineal
</font>
<p></p>
<font size=6>
Cuaderno de ejercicios - Tema 2a
</font>


---
#Ejercicio 1
---

Dado el siguiente sistema de ecuaciones lineales:

>$2x_1 - 3x_2 + 4x_3 + x_4 = 2$
>
>$x_1 - 3x_3 - x_4 = \frac{3}{2}$
>
>$4x_1 + x_2 - 2x_3 = 3$
>
>$2x_1 - x_2 + 6x_3 + 2x_4 = 1$

**a) Escribe la matriz de coeficientes del sistema y calcula su determinante. ¿Qué se puede afirmar sobre la solución del sistema de ecuaciones a partir de este resultado?**

In [ ]:
# Se importan las librerias necesarias
import numpy as np
import fractions
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})

In [ ]:
# Matriz de coeficientes A
A = np.array([[2, -3, 4, 1], [1, 0, -3, -1], [4, 1, -2, 0], [2, -1, 6, 2]])
print(A)

[[2 -3 4 1]
 [1 0 -3 -1]
 [4 1 -2 0]
 [2 -1 6 2]]


In [ ]:
# Cálculo del determinante
print(np.linalg.det(A))

-9.999999999999998


**b)	Resuelve el sistema utilizando la matriz inversa.**

Se resolvera el sistema usando $x = A^{-1}b$

In [ ]:
# Vector de términos independientes
b = np.array([2, 3/2, 3, 1])
print(b)

[2 3/2 3 1]


In [ ]:
# Calculo de la inversa de A
Ainv = np.linalg.inv(A)
print(Ainv)

[[-1/5 4/5 -1/10 1/2]
 [-4/5 6/5 -2/5 1]
 [-4/5 11/5 -9/10 3/2]
 [11/5 -34/5 13/5 -4]]


Para comprobar el resultado se puede utilizar:

$AA^{-1} = A^{-1}A=I_n$

In [ ]:
# Comprobación del resultado
print(np.matmul(Ainv, A))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
# Solución del sistema
x = np.matmul(Ainv, b)
print(x)

[1 0 1/2 -2]


**c)	Resuelve el sistema aplicando el método de Gauss -Jordan. Registra el procedimiento paso a paso y la solución.**

In [ ]:
# Construir la matriz aumentada del sistema [A|b]
Au = np.array([[2, -3, 4, 1, 2], [1, 0, -3, -1, 3/2], [2, 0, -6, -2, 3], [2, -1, 6, 2, 1]])
print(Au)

[[2 -3 4 1 2]
 [1 0 -3 -1 3/2]
 [2 0 -6 -2 3]
 [2 -1 6 2 1]]


In [ ]:
# Se obtiene la matriz escalonada reducida por filas
Au[0] = (1/2)*Au[0]
print(Au)

[[1 -3/2 2 1/2 1]
 [1 0 -3 -1 3/2]
 [2 0 -6 -2 3]
 [2 -1 6 2 1]]


In [ ]:
Au[1] = Au[1] + (-1)*Au[0]
Au[2] = Au[2] + (-2)*Au[0]
Au[3] = Au[3] + (-2)*Au[0]
print(Au)

[[1 -3/2 2 1/2 1]
 [0 3/2 -5 -3/2 1/2]
 [0 3 -10 -3 1]
 [0 2 2 1 -1]]


In [ ]:
Au[1] = (2/3)*Au[1]
print(Au)

[[1 -3/2 2 1/2 1]
 [0 1 -10/3 -1 1/3]
 [0 3 -10 -3 1]
 [0 2 2 1 -1]]


In [ ]:
Au[0] = Au[0] + (3/2)*Au[1]
Au[2] = Au[2] + (-3)*Au[1]
Au[3] = Au[3] + (-2)*Au[1]
print(Au)

[[1 0 -3 -1 3/2]
 [0 1 -10/3 -1 1/3]
 [0 0 0 0 0]
 [0 0 26/3 3 -5/3]]


In [ ]:
Au[[2, 3], :] = Au[[3, 2], :]
print(Au)

[[1 0 -3 -1 3/2]
 [0 1 -10/3 -1 1/3]
 [0 0 26/3 3 -5/3]
 [0 0 0 0 0]]


In [ ]:
Au[2] = (3/26)*Au[2]
print(Au)

[[1 0 -3 -1 3/2]
 [0 1 -10/3 -1 1/3]
 [0 0 1 9/26 -5/26]
 [0 0 0 0 0]]


In [ ]:
Au[0] = Au[0] + (3)*Au[2]
Au[1] = Au[1] + (10/3)*Au[2]
print(Au)

[[1 0 0 1/26 12/13]
 [0 1 0 2/13 -4/13]
 [0 0 1 9/26 -5/26]
 [0 0 0 0 0]]


In [ ]:
Au[3] = (-4/1)*Au[3]
print(Au)

[[1 0 0 1/8 3/4]
 [0 1 0 1/4 -1/2]
 [0 0 1 3/8 -1/4]
 [0 0 0 1 -2]]


In [ ]:
Au[0] = Au[0] + (-1/8)*Au[3]
Au[1] = Au[1] + (-1/4)*Au[3]
Au[2] = Au[2] + (-3/8)*Au[3]
print(Au)

[[1 0 0 0 1]
 [0 1 0 0 0]
 [0 0 1 0 1/2]
 [0 0 0 1 -2]]


In [ ]:
solucion = np.linalg.solve(A, b)
print(solucion)

[1 0 1/2 -2]


**d)	Explica qué hace el método ```rref``` de Sympy. Ilustra la explicación con el sistema de ecuaciones dado.**

In [ ]:
# Construir la matriz aumentada del sistema [A|b]
import sympy as sp
Au2 = sp.Matrix([[2, -3, 4, 1, 2], [1, 0, -3, -1, 3/2], [4, 1, -2, 0, 3], [2, -1, 6, 2, 1]])
print(Au2)

Matrix([[2, -3, 4, 1, 2], [1, 0, -3, -1, 1.50000000000000], [4, 1, -2, 0, 3], [2, -1, 6, 2, 1]])


In [ ]:
print(Au2.rref())

(Matrix([
[1, 0, 0, 0,  1.0],
[0, 1, 0, 0,    0],
[0, 0, 1, 0,  0.5],
[0, 0, 0, 1, -2.0]]), (0, 1, 2, 3))


---
#Ejercicio 2
---

Responde las mismas preguntas del Ejercicio 1 para el siguiente sistema de ecuaciones:

>$3x+6y-9z=-4$
>
>$2x-3y+z=-3$
>
>$x + 2y - 3z = -12$


**a) Escribe la matriz de coeficientes del sistema y calcula su determinante. ¿Qué se puede afirmar sobre la solución del sistema de ecuaciones a partir de este resultado?**

In [4]:
import numpy as np
import fractions
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})

B = np.array([[3, 6, -9], [2, -3, 1], [1, 2, -3]])
print(B)
# terminos independientes
b = np.array([-4, -3, -12])

determinante = np.linalg.det(B)
print(f'El determinante es: {determinante}')

[[3 6 -9]
 [2 -3 1]
 [1 2 -3]]
El determinante es: 0.0


**b)	Resuelve el sistema utilizando la matriz inversa.**

Se resolvera el sistema usando $x = B^{-1}b$

In [9]:

try:
    if determinante != 0:
        # matriz no singular
        Binv = np.linalg.inv(B)
        print(Binv)
        print()

        # BB^{-1} = B^{-1}B=I_n
        print('# Comprobación del resultado')
        print(np.matmul(Binv, B))
    else:
        print('La matriz es singular')
except Exception as e:
    print(f'Ha ocurrido una excepción: {e}')
# Calculo de la inversa de B


La matriz es singular


Para comprobar el resultado se puede utilizar:

$BB^{-1} = B^{-1}B=I_n$

**c)	Explica qué hace el método ```rref``` de Sympy. Ilustra la explicación con el sistema de ecuaciones dado.**

In [13]:
# Construir la matriz aumentada del sistema [B|b]
import sympy as sp
Bau = sp.Matrix([[3, 6, -9, -4], [2, -3, 1, -3], [1, 2, -3, -12]])
print(Bau)

print(Bau.rref())

Matrix([[3, 6, -9, -4], [2, -3, 1, -3], [1, 2, -3, -12]])
(Matrix([
[1, 0, -1, 0],
[0, 1, -1, 0],
[0, 0,  0, 1]]), (0, 1, 3))


**d) Eliminación Gaussinana:**

In [16]:
import numpy as np
Bau = np.array([[3, 6, -9, -4], [2, -3, 1, -3], [1, 2, -3, -12]])
print(Bau)

print('# 0. intercambiamos F1 <--> F3')
Bau = np.array([[1, 2, -3, -12], [2, -3, 1, -3], [3, 6, -9, -4]])
print(Bau)

print('# 1. para obtener el primer 0 hacemos: F2 - 2F1')
F2 = Bau[1] - 2*Bau[0]
Bau[1] = F2
print(Bau)
print()


print('# 2. para obtener el segundo 0 hacemos: F3 - 3F1')
F3 = Bau[2] - 3*Bau[0]
Bau[2] = F3
print(Bau)
print()


[[3 6 -9 -4]
 [2 -3 1 -3]
 [1 2 -3 -12]]
# 0. intercambiamos F1 <--> F3
[[1 2 -3 -12]
 [2 -3 1 -3]
 [3 6 -9 -4]]
# 1. para obtener el primer 0 hacemos: F2 - 2F1
[[1 2 -3 -12]
 [0 -7 7 21]
 [3 6 -9 -4]]

# 2. para obtener el segundo 0 hacemos: F3 - 3F1
[[1 2 -3 -12]
 [0 -7 7 21]
 [0 0 0 32]]

